/** Transform (3D layout) preset gallery, transcribed verbatim from
 * screenshot-studio (components/editor/sections/TransformsGallery.tsx). 39
 * presets across 7 categories. Note: these use the reference's own
 * perspective scale (up to 2400px); the fine-tune Depth slider uses a narrower
 * range, matching the upstream's own two-scale behaviour. */
import type { Transform3D } from "./types";

export interface TransformPresetEntry {
	id: string;
	name: string;
	transform: Transform3D;
}

export interface TransformPresetCategory {
	name: string;
	presets: TransformPresetEntry[];
}

function t3d(id: string, name: string, transform: Transform3D): TransformPresetEntry {
	return { id, name, transform };
}

export const TRANSFORM_PRESET_CATEGORIES: TransformPresetCategory[] = [
	{
		name: "Popular",
		presets: [
			t3d("Popular · Default", "Default", {
				perspective: 2400,
				rotateX: 0,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: 0,
				scale: 1,
			}),
			t3d("Popular · SaaS Hero", "SaaS Hero", {
				perspective: 2400,
				rotateX: 8,
				rotateY: -6,
				rotateZ: 0,
				translateX: 0,
				translateY: -2,
				scale: 0.98,
			}),
			t3d("Popular · Product Shot", "Product Shot", {
				perspective: 2000,
				rotateX: 5,
				rotateY: 12,
				rotateZ: 0,
				translateX: 3,
				translateY: -1,
				scale: 0.97,
			}),
			t3d("Popular · App Preview", "App Preview", {
				perspective: 2400,
				rotateX: 12,
				rotateY: -10,
				rotateZ: 0,
				translateX: -2,
				translateY: -3,
				scale: 0.96,
			}),
			t3d("Popular · Clean Angle", "Clean Angle", {
				perspective: 2400,
				rotateX: 6,
				rotateY: 8,
				rotateZ: -2,
				translateX: 2,
				translateY: -1,
				scale: 0.98,
			}),
			t3d("Popular · Landing Page", "Landing Page", {
				perspective: 1800,
				rotateX: 15,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: -5,
				scale: 0.95,
			}),
		],
	},
	{
		name: "Basic",
		presets: [
			t3d("Basic · Tilt Left", "Tilt Left", {
				perspective: 2400,
				rotateX: 0,
				rotateY: 0,
				rotateZ: -8,
				translateX: 0,
				translateY: 0,
				scale: 0.95,
			}),
			t3d("Basic · Tilt Right", "Tilt Right", {
				perspective: 2400,
				rotateX: 0,
				rotateY: 0,
				rotateZ: 8,
				translateX: 0,
				translateY: 0,
				scale: 0.95,
			}),
			t3d("Basic · Subtle Left", "Subtle Left", {
				perspective: 2400,
				rotateX: 3,
				rotateY: -8,
				rotateZ: 0,
				translateX: -2,
				translateY: 0,
				scale: 1,
			}),
			t3d("Basic · Subtle Right", "Subtle Right", {
				perspective: 2400,
				rotateX: 3,
				rotateY: 8,
				rotateZ: 0,
				translateX: 2,
				translateY: 0,
				scale: 1,
			}),
			t3d("Basic · Lean Back", "Lean Back", {
				perspective: 2400,
				rotateX: -15,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: 5,
				scale: 0.98,
			}),
			t3d("Basic · Lean Forward", "Lean Forward", {
				perspective: 2400,
				rotateX: 18,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: -4,
				scale: 0.97,
			}),
		],
	},
	{
		name: "Dramatic",
		presets: [
			t3d("Dramatic · Dramatic Left", "Dramatic Left", {
				perspective: 2400,
				rotateX: 10,
				rotateY: -20,
				rotateZ: 8,
				translateX: -4,
				translateY: -2,
				scale: 0.95,
			}),
			t3d("Dramatic · Dramatic Right", "Dramatic Right", {
				perspective: 2400,
				rotateX: 10,
				rotateY: 20,
				rotateZ: -8,
				translateX: 4,
				translateY: -2,
				scale: 0.95,
			}),
			t3d("Dramatic · Hero Left", "Hero Left", {
				perspective: 1800,
				rotateX: 8,
				rotateY: -25,
				rotateZ: 5,
				translateX: -6,
				translateY: 0,
				scale: 0.92,
			}),
			t3d("Dramatic · Hero Right", "Hero Right", {
				perspective: 1800,
				rotateX: 8,
				rotateY: 25,
				rotateZ: -5,
				translateX: 6,
				translateY: 0,
				scale: 0.92,
			}),
			t3d("Dramatic · Showcase L", "Showcase L", {
				perspective: 1500,
				rotateX: 15,
				rotateY: -30,
				rotateZ: 5,
				translateX: -10,
				translateY: -3,
				scale: 0.88,
			}),
			t3d("Dramatic · Showcase R", "Showcase R", {
				perspective: 1500,
				rotateX: 15,
				rotateY: 30,
				rotateZ: -5,
				translateX: 10,
				translateY: -3,
				scale: 0.88,
			}),
		],
	},
	{
		name: "Perspective",
		presets: [
			t3d("Perspective · Top Down", "Top Down", {
				perspective: 2400,
				rotateX: 40,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: -5,
				scale: 0.95,
			}),
			t3d("Perspective · Bottom Up", "Bottom Up", {
				perspective: 2400,
				rotateX: -35,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: 8,
				scale: 0.95,
			}),
			t3d("Perspective · Lay Flat", "Lay Flat", {
				perspective: 2400,
				rotateX: 55,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: -12,
				scale: 0.8,
			}),
			t3d("Perspective · Magazine", "Magazine", {
				perspective: 2400,
				rotateX: 58,
				rotateY: 8,
				rotateZ: 38,
				translateX: 0,
				translateY: -8,
				scale: 0.82,
			}),
			t3d("Perspective · Isometric L", "Isometric L", {
				perspective: 2400,
				rotateX: 45,
				rotateY: 0,
				rotateZ: -45,
				translateX: 0,
				translateY: -5,
				scale: 0.9,
			}),
			t3d("Perspective · Isometric R", "Isometric R", {
				perspective: 2400,
				rotateX: 38.4,
				rotateY: -6.4,
				rotateZ: 25,
				translateX: 0,
				translateY: -5.8,
				scale: 0.9,
			}),
			t3d("Perspective · Isometric Top", "Isometric Top", {
				perspective: 2400,
				rotateX: 50,
				rotateY: 0,
				rotateZ: 45,
				translateX: 0,
				translateY: -8,
				scale: 0.85,
			}),
			t3d("Perspective · Table Left", "Table Left", {
				perspective: 2400,
				rotateX: 55,
				rotateY: 10,
				rotateZ: -35,
				translateX: 0,
				translateY: -10,
				scale: 0.8,
			}),
		],
	},
	{
		name: "Zoom",
		presets: [
			t3d("Zoom · Zoom Center", "Zoom Center", {
				perspective: 2400,
				rotateX: 0,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: 0,
				scale: 1.2,
			}),
			t3d("Zoom · Zoom Left", "Zoom Left", {
				perspective: 2400,
				rotateX: 0,
				rotateY: 8,
				rotateZ: 0,
				translateX: 15,
				translateY: 0,
				scale: 1.15,
			}),
			t3d("Zoom · Zoom Right", "Zoom Right", {
				perspective: 2400,
				rotateX: 0,
				rotateY: -8,
				rotateZ: 0,
				translateX: -15,
				translateY: 0,
				scale: 1.15,
			}),
			t3d("Zoom · Zoom Top", "Zoom Top", {
				perspective: 2400,
				rotateX: 5,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: 12,
				scale: 1.15,
			}),
			t3d("Zoom · Zoom Bottom", "Zoom Bottom", {
				perspective: 2400,
				rotateX: -5,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: -12,
				scale: 1.15,
			}),
		],
	},
	{
		name: "Half Section",
		presets: [
			t3d("Half Section · Half Left", "Half Left", {
				perspective: 2400,
				rotateX: 0,
				rotateY: 12,
				rotateZ: -2,
				translateX: 20,
				translateY: 0,
				scale: 1.25,
			}),
			t3d("Half Section · Half Right", "Half Right", {
				perspective: 2400,
				rotateX: 0,
				rotateY: -12,
				rotateZ: 2,
				translateX: -20,
				translateY: 0,
				scale: 1.25,
			}),
			t3d("Half Section · Half Top", "Half Top", {
				perspective: 2400,
				rotateX: 10,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: 18,
				scale: 1.25,
			}),
			t3d("Half Section · Half Bottom", "Half Bottom", {
				perspective: 2400,
				rotateX: -10,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: -18,
				scale: 1.25,
			}),
		],
	},
	{
		name: "Float",
		presets: [
			t3d("Float · Float Up", "Float Up", {
				perspective: 2400,
				rotateX: 12,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: -10,
				scale: 1.05,
			}),
			t3d("Float · Float Down", "Float Down", {
				perspective: 2400,
				rotateX: -8,
				rotateY: 0,
				rotateZ: 0,
				translateX: 0,
				translateY: 10,
				scale: 1.05,
			}),
			t3d("Float · Hover Left", "Hover Left", {
				perspective: 2000,
				rotateX: 5,
				rotateY: -15,
				rotateZ: 3,
				translateX: -8,
				translateY: -5,
				scale: 1.02,
			}),
			t3d("Float · Hover Right", "Hover Right", {
				perspective: 2000,
				rotateX: 5,
				rotateY: 15,
				rotateZ: -3,
				translateX: 8,
				translateY: -5,
				scale: 1.02,
			}),
		],
	},
];
