import type { BackgroundType } from "../stores/editor-store.svelte";
export type Preset = {
	id: string;
	label: string;
	category: string;
	aspect: string;
	description?: string;
	bg: BackgroundType;
	value?: string;
	padding: number;
	blur: number;
	layout?: "auto" | "crop";
	keywords?: string[];
};
export const PRESETS: Preset[] = [
	// Studio looks
	{
		id: "studio",
		label: "Studio",
		category: "Studio",
		aspect: "Source",
		description: "Soft blue gradient, centred padding",
		bg: "gradient",
		value: "linear-gradient(135deg, #0f172a 0%, #1d4ed8 100%)",
		padding: 3,
		blur: 18,
		layout: "auto",
		keywords: ["gradient", "blue"],
	},
	{
		id: "focus",
		label: "Focus",
		category: "Studio",
		aspect: "Source",
		description: "Deep navy, minimal frame",
		bg: "color",
		value: "#0b1120",
		padding: 2,
		blur: 0,
		layout: "auto",
		keywords: ["solid", "dark"],
	},
	{
		id: "spotlight",
		label: "Spotlight",
		category: "Studio",
		aspect: "Source",
		description: "Wallpaper backdrop with strong blur",
		bg: "wallpaper",
		value: "asset:wallpaper7",
		padding: 5,
		blur: 36,
		layout: "auto",
		keywords: ["wallpaper", "blur"],
	},
	{
		id: "edge",
		label: "Edge to Edge",
		category: "Studio",
		aspect: "Source",
		description: "No padding, full bleed",
		bg: "color",
		value: "#020617",
		padding: 0,
		blur: 0,
		layout: "crop",
		keywords: ["bleed", "full"],
	},
	// Instagram
	{
		id: "ig-post",
		label: "Post",
		category: "Instagram",
		aspect: "1:1",
		description: "Square feed post",
		bg: "gradient",
		value: "linear-gradient(135deg, #833ab4 0%, #fd1d1d 50%, #fcb045 100%)",
		padding: 6,
		blur: 24,
		layout: "auto",
		keywords: ["instagram", "ig", "square", "feed"],
	},
	{
		id: "ig-story",
		label: "Story",
		category: "Instagram",
		aspect: "9:16",
		description: "Vertical full-screen story",
		bg: "gradient",
		value: "linear-gradient(180deg, #1e1b4b 0%, #831843 100%)",
		padding: 8,
		blur: 28,
		layout: "auto",
		keywords: ["instagram", "ig", "vertical", "9:16"],
	},
	{
		id: "ig-reel",
		label: "Reel",
		category: "Instagram",
		aspect: "9:16",
		description: "Reels-friendly vertical frame",
		bg: "color",
		value: "#0a0a0a",
		padding: 4,
		blur: 0,
		layout: "auto",
		keywords: ["instagram", "ig", "reel", "vertical"],
	},
	{
		id: "ig-landscape",
		label: "Landscape",
		category: "Instagram",
		aspect: "1.91:1",
		description: "Wide feed post",
		bg: "gradient",
		value: "linear-gradient(135deg, #f472b6 0%, #8b5cf6 100%)",
		padding: 4,
		blur: 16,
		layout: "auto",
		keywords: ["instagram", "ig", "landscape", "wide"],
	},
	// YouTube
	{
		id: "yt-standard",
		label: "Standard",
		category: "YouTube",
		aspect: "16:9",
		description: "Classic 1080p / 4K landscape",
		bg: "color",
		value: "#0f0f0f",
		padding: 3,
		blur: 0,
		layout: "auto",
		keywords: ["youtube", "yt", "16:9", "landscape"],
	},
	{
		id: "yt-shorts",
		label: "Shorts",
		category: "YouTube",
		aspect: "9:16",
		description: "Vertical mobile-first",
		bg: "gradient",
		value: "linear-gradient(180deg, #7f1d1d 0%, #0f0f0f 100%)",
		padding: 6,
		blur: 20,
		layout: "auto",
		keywords: ["youtube", "yt", "shorts", "vertical"],
	},
	{
		id: "yt-thumbnail",
		label: "Thumbnail Safe",
		category: "YouTube",
		aspect: "16:9",
		description: "Extra padding for thumbnail safe area",
		bg: "gradient",
		value: "linear-gradient(135deg, #dc2626 0%, #1e293b 100%)",
		padding: 5,
		blur: 12,
		layout: "auto",
		keywords: ["youtube", "yt", "thumbnail"],
	},
	// X / Twitter
	{
		id: "x-post",
		label: "Post",
		category: "X / Twitter",
		aspect: "16:9",
		description: "Inline timeline video",
		bg: "color",
		value: "#15202b",
		padding: 3,
		blur: 0,
		layout: "auto",
		keywords: ["twitter", "x", "post", "16:9"],
	},
	{
		id: "x-square",
		label: "Square",
		category: "X / Twitter",
		aspect: "1:1",
		description: "Mobile-friendly square",
		bg: "gradient",
		value: "linear-gradient(135deg, #1d9bf0 0%, #0f172a 100%)",
		padding: 5,
		blur: 18,
		layout: "auto",
		keywords: ["twitter", "x", "square"],
	},
	{
		id: "x-vertical",
		label: "Vertical",
		category: "X / Twitter",
		aspect: "9:16",
		description: "Vertical autoplay clip",
		bg: "color",
		value: "#000000",
		padding: 4,
		blur: 0,
		layout: "auto",
		keywords: ["twitter", "x", "vertical"],
	},
	// TikTok
	{
		id: "tt-feed",
		label: "Feed",
		category: "TikTok",
		aspect: "9:16",
		description: "Standard For-You feed clip",
		bg: "gradient",
		value: "linear-gradient(180deg, #fe2c55 0%, #25f4ee 100%)",
		padding: 6,
		blur: 22,
		layout: "auto",
		keywords: ["tiktok", "tt", "vertical"],
	},
	// LinkedIn
	{
		id: "li-square",
		label: "Square",
		category: "LinkedIn",
		aspect: "1:1",
		description: "High-engagement square post",
		bg: "color",
		value: "#0a66c2",
		padding: 5,
		blur: 0,
		layout: "auto",
		keywords: ["linkedin", "li", "square"],
	},
	{
		id: "li-landscape",
		label: "Landscape",
		category: "LinkedIn",
		aspect: "1.91:1",
		description: "Native landscape feed video",
		bg: "gradient",
		value: "linear-gradient(135deg, #0a66c2 0%, #0f172a 100%)",
		padding: 4,
		blur: 14,
		layout: "auto",
		keywords: ["linkedin", "li", "landscape"],
	},
];
