/**
 * Editor Store — Central reactive state for the video editor.
 * Uses Svelte 5 runes ($state) for granular reactivity.
 */

import type { CursorSampleLike } from '../cursor/smoothing';
import { EASE, type Easing } from '../easing/cubic-bezier';

export type BackgroundType = 'wallpaper' | 'image' | 'color' | 'gradient';


export interface WallpaperOption {
	/** Full-resolution source, used when compositing the canvas. */
	src: string;
	/** Small WebP preview (~3 KB). Generated by scripts/build-wallpaper-thumbs.mjs. Used in the picker grid. */
	thumb: string;
	label: string;
}

export interface ZoomRegion {
	id: string;
	start: number; // seconds
	end: number; // seconds
	scale: number; // 1.0 - 3.0
	easeIn: Easing;
	easeOut: Easing;
	rampIn: number; // seconds spent ramping from 1.0 → scale
	rampOut: number; // seconds spent ramping from scale → 1.0
}

export const DEFAULT_ZOOM_RAMP = 0.35;

export interface CursorSettings {
	enabled: boolean;
	size: number; // 1-5 scale
	smoothing: number; // 0-100 → Gaussian σ in ms (0 = raw capture, 100 ≈ 150 ms)
	snapToClicks: boolean; // anchor smoothed path to exact click x/y around mouse-down
	snapWindowMs: number; // half-width (ms) of the snap anchor — 0..200
	highlightClicks: boolean;
	highlightColor: string;
	highlightOpacity: number; // 0-100
	hideWhenIdle: boolean;
	idleTimeout: number; // seconds
}

export interface BackgroundSelection {
	type: BackgroundType;
	value: string;
}

export interface AudioSettings {
	volume: number; // 0-100
	muted: boolean;
	fadeIn: number; // seconds
	fadeOut: number; // seconds
}

export type WatermarkPosition =
	| 'top-left'
	| 'top-right'
	| 'bottom-left'
	| 'bottom-right';

export interface WatermarkSettings {
	enabled: boolean;
	imagePath: string;
	imageSrc: string;
	opacity: number; // 0-100
	scale: number; // 8-35 percent of frame width
	position: WatermarkPosition;
	inset: number; // pixels
}

export interface VideoMetadata {
	duration: number;
	width: number;
	height: number;
	fps: number;
	codec: string;
	sizeBytes: number;
}

export interface EditorRenderState {
	trimStart: number;
	trimEnd: number;
	backgroundType: BackgroundType;
	backgroundValue: string;
	backgroundBlur: number;
	padding: number;
	borderRadius: number;
	cursorEnabled: boolean;
	cursorSize: number;
	cursorSmoothing: number;
	cursorSnapToClicks: boolean;
	cursorSnapWindowMs: number;
	cursorHighlightClicks: boolean;
	cursorHighlightColor: string;
	cursorHighlightOpacity: number;
	cursorHideWhenIdle: boolean;
	cursorIdleTimeout: number;
	zoomRegions: Array<{
		start: number;
		end: number;
		scale: number;
		easeIn: Easing;
		easeOut: Easing;
		rampIn: number;
		rampOut: number;
	}>;
	cursorMotionEasing: Easing | null;
}

export type ExportFormat = 'mp4' | 'gif' | 'webm';
export type ExportQuality = 'small' | 'hd' | '4k' | 'source';

export type LayoutMode = 'auto' | 'crop';

export type EditorWindowBehavior = 'navigate' | 'new-window';

export const WALLPAPERS: WallpaperOption[] = Array.from({ length: 23 }, (_, i) => ({
	src: `/backgrounds/wallpapers/wallpaper${i + 1}.png`,
	thumb: `/backgrounds/thumbs/wallpaper${i + 1}.webp`,
	label: `Wallpaper ${i + 1}`,
}));

export const GRADIENT_PRESETS = [
	{ label: 'Sunset', value: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' },
	{ label: 'Ocean', value: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)' },
	{ label: 'Forest', value: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)' },
	{ label: 'Lavender', value: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)' },
	{ label: 'Midnight', value: 'linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)' },
	{ label: 'Ember', value: 'linear-gradient(135deg, #f83600 0%, #f9d423 100%)' },
];

export const COLOR_PRESETS = [
	'#000000', '#1a1a2e', '#16213e', '#0f3460',
	'#533483', '#e94560', '#f38181', '#fce38a',
	'#eaffd0', '#95e1d3', '#ffffff', '#f5f5f5',
];

function generateId(): string {
	return Math.random().toString(36).substring(2, 9);
}

/**
 * Creates an editor store instance.
 * Call once per editor page mount, or use a singleton.
 */
export function createEditorStore() {
	// Video source
	let videoPath = $state('');
	let metadata = $state<VideoMetadata | null>(null);
	let thumbnailStrip = $state<string[]>([]);

	// Playback
	let currentTime = $state(0);
	let isPlaying = $state(false);

	// Trim
	let trimStart = $state(0);
	let trimEnd = $state(0); // will be set to duration on load

	// Background
	let backgroundType = $state<BackgroundType>('wallpaper');
	let backgroundValue = $state(WALLPAPERS[0].src);
	let backgroundBlur = $state(40);
	let padding = $state(32);
	let borderRadius = $state(0); // 0..50 (% of shorter video edge)

	// Layout
	let layoutMode = $state<LayoutMode>('auto');

	// Raw cursor samples, shared between the preview (which runs the actual
	// compositor) and the Cursor panel (which needs them for the trajectory
	// minimap). Set by VideoPreview on load; read-only elsewhere.
	let cursorSamplesRaw = $state<CursorSampleLike[]>([]);

	// Zoom regions
	let zoomRegions = $state<ZoomRegion[]>([]);
	let selectedZoomRegionId = $state<string | null>(null);

	// Global cursor motion easing. `null` means linear (today's behaviour);
	// a non-null curve reshapes the per-sample lerp in the WebGL preview.
	let cursorMotionEasing = $state<Easing | null>(null);

	// Cursor settings
	let cursorSettings = $state<CursorSettings>({
		enabled: true,
		size: 3,
		smoothing: 50,
		snapToClicks: true,
		snapWindowMs: 80,
		highlightClicks: true,
		highlightColor: '#3b82f6',
		highlightOpacity: 40,
		hideWhenIdle: false,
		idleTimeout: 3,
	});

	// Audio settings
	let audioSettings = $state<AudioSettings>({
		volume: 100,
		muted: false,
		fadeIn: 0,
		fadeOut: 0,
	});

	// Watermark settings
	let watermarkSettings = $state<WatermarkSettings>({
		enabled: false,
		imagePath: '',
		imageSrc: '',
		opacity: 70,
		scale: 18,
		position: 'bottom-right',
		inset: 24,
	});

	// Export
	let exportFormat = $state<ExportFormat>('mp4');
	let exportQuality = $state<ExportQuality>('hd');
	let exportProgress = $state<number | null>(null);
	let isExporting = $state(false);

	// Undo/Redo stacks (simplified — stores snapshots of key settings)
	let undoStack = $state<string[]>([]);
	let redoStack = $state<string[]>([]);

	// Timeline zoom
	let timelineZoom = $state(1); // 1x = fit to width

	function getSettingsSnapshot(): string {
		return JSON.stringify({
			backgroundType,
			backgroundValue,
			backgroundBlur,
			padding,
			borderRadius,
			trimStart,
			trimEnd,
			zoomRegions,
			cursorSettings,
			audioSettings,
			watermarkSettings,
			layoutMode,
			cursorMotionEasing,
		});
	}

	const MAX_UNDO_HISTORY = 50;

	function pushUndoState() {
		undoStack = [...undoStack, getSettingsSnapshot()].slice(-MAX_UNDO_HISTORY);
		redoStack = [];
	}

	function undo() {
		if (undoStack.length === 0) return;
		const prev = undoStack[undoStack.length - 1];
		redoStack = [...redoStack, getSettingsSnapshot()];
		undoStack = undoStack.slice(0, -1);
		applySnapshot(prev);
	}

	function redo() {
		if (redoStack.length === 0) return;
		const next = redoStack[redoStack.length - 1];
		undoStack = [...undoStack, getSettingsSnapshot()];
		redoStack = redoStack.slice(0, -1);
		applySnapshot(next);
	}

	function applySnapshot(json: string) {
		const s = JSON.parse(json);
		backgroundType = s.backgroundType;
		backgroundValue = s.backgroundValue;
		backgroundBlur = s.backgroundBlur;
		padding = s.padding;
		borderRadius = s.borderRadius ?? 0;
		trimStart = s.trimStart;
		trimEnd = s.trimEnd;
		zoomRegions = s.zoomRegions;
		cursorSettings = s.cursorSettings;
		audioSettings = s.audioSettings ?? audioSettings;
		watermarkSettings = s.watermarkSettings ?? watermarkSettings;
		layoutMode = s.layoutMode;
		cursorMotionEasing = s.cursorMotionEasing ?? null;
	}

	function addZoomRegion(start: number, end: number, scale = 1.5) {
		pushUndoState();
		const region: ZoomRegion = {
			id: generateId(),
			start,
			end,
			scale,
			easeIn: { ...EASE },
			easeOut: { ...EASE },
			rampIn: DEFAULT_ZOOM_RAMP,
			rampOut: DEFAULT_ZOOM_RAMP,
		};
		zoomRegions = [...zoomRegions, region];
		selectedZoomRegionId = region.id;
	}

	function setBackground(selection: BackgroundSelection) {
		const hasChanged =
			backgroundType !== selection.type || backgroundValue !== selection.value;
		if (!hasChanged) return;
		pushUndoState();
		backgroundType = selection.type;
		backgroundValue = selection.value;
	}

	function updateCursorSettings(updates: Partial<CursorSettings>) {
		cursorSettings = { ...cursorSettings, ...updates };
	}

	function updateAudioSettings(updates: Partial<AudioSettings>) {
		audioSettings = { ...audioSettings, ...updates };
	}

	function updateWatermarkSettings(updates: Partial<WatermarkSettings>) {
		watermarkSettings = { ...watermarkSettings, ...updates };
	}

	function removeZoomRegion(id: string) {
		pushUndoState();
		zoomRegions = zoomRegions.filter((z) => z.id !== id);
		if (selectedZoomRegionId === id) selectedZoomRegionId = null;
	}

	function updateZoomRegion(id: string, updates: Partial<ZoomRegion>) {
		zoomRegions = zoomRegions.map((z) => (z.id === id ? { ...z, ...updates } : z));
	}

	function selectZoomRegion(id: string | null) {
		selectedZoomRegionId = id;
	}

	function reset() {
		currentTime = 0;
		isPlaying = false;
		trimStart = 0;
		trimEnd = metadata?.duration ?? 0;
		backgroundType = 'wallpaper';
		backgroundValue = WALLPAPERS[0].src;
		backgroundBlur = 40;
		padding = 32;
		borderRadius = 0;
		layoutMode = 'auto';
		zoomRegions = [];
		selectedZoomRegionId = null;
		cursorMotionEasing = null;
		cursorSettings = {
			enabled: true,
			size: 3,
			smoothing: 50,
			snapToClicks: true,
			snapWindowMs: 80,
			highlightClicks: true,
			highlightColor: '#3b82f6',
			highlightOpacity: 40,
			hideWhenIdle: false,
			idleTimeout: 3,
		};
		audioSettings = {
			volume: 100,
			muted: false,
			fadeIn: 0,
			fadeOut: 0,
		};
		watermarkSettings = {
			enabled: false,
			imagePath: '',
			imageSrc: '',
			opacity: 70,
			scale: 18,
			position: 'bottom-right',
			inset: 24,
		};
		exportQuality = 'hd';
		undoStack = [];
		redoStack = [];
	}

	function toRenderState(): EditorRenderState {
		return {
			trimStart,
			trimEnd,
			backgroundType,
			backgroundValue,
			backgroundBlur,
			padding,
			borderRadius,
			cursorEnabled: cursorSettings.enabled,
			cursorSize: cursorSettings.size,
			cursorSmoothing: cursorSettings.smoothing,
			cursorSnapToClicks: cursorSettings.snapToClicks,
			cursorSnapWindowMs: cursorSettings.snapWindowMs,
			cursorHighlightClicks: cursorSettings.highlightClicks,
			cursorHighlightColor: cursorSettings.highlightColor,
			cursorHighlightOpacity: cursorSettings.highlightOpacity,
			cursorHideWhenIdle: cursorSettings.hideWhenIdle,
			cursorIdleTimeout: cursorSettings.idleTimeout,
			zoomRegions: zoomRegions.map((region) => ({
				start: region.start,
				end: region.end,
				scale: region.scale,
				easeIn: region.easeIn,
				easeOut: region.easeOut,
				rampIn: region.rampIn,
				rampOut: region.rampOut,
			})),
			cursorMotionEasing,
		};
	}

	function loadRenderState(state: Partial<EditorRenderState>) {
		trimStart = state.trimStart ?? 0;
		trimEnd = state.trimEnd ?? metadata?.duration ?? 0;
		backgroundType = state.backgroundType ?? 'color';
		backgroundValue = state.backgroundValue ?? '#111111';
		backgroundBlur = state.backgroundBlur ?? 0;
		padding = state.padding ?? 0;
		borderRadius = state.borderRadius ?? 0;
		cursorSettings = {
			...cursorSettings,
			enabled: state.cursorEnabled ?? cursorSettings.enabled,
			size: state.cursorSize ?? cursorSettings.size,
			smoothing: state.cursorSmoothing ?? cursorSettings.smoothing,
			snapToClicks: state.cursorSnapToClicks ?? cursorSettings.snapToClicks,
			snapWindowMs: state.cursorSnapWindowMs ?? cursorSettings.snapWindowMs,
			highlightClicks:
				state.cursorHighlightClicks ?? cursorSettings.highlightClicks,
			highlightColor:
				state.cursorHighlightColor ?? cursorSettings.highlightColor,
			highlightOpacity:
				state.cursorHighlightOpacity ?? cursorSettings.highlightOpacity,
			hideWhenIdle:
				state.cursorHideWhenIdle ?? cursorSettings.hideWhenIdle,
			idleTimeout:
				state.cursorIdleTimeout ?? cursorSettings.idleTimeout,
		};
		zoomRegions = (state.zoomRegions ?? []).map((region) => ({
			id: generateId(),
			start: region.start,
			end: region.end,
			scale: region.scale,
			easeIn: region.easeIn ?? { ...EASE },
			easeOut: region.easeOut ?? { ...EASE },
			rampIn: region.rampIn ?? DEFAULT_ZOOM_RAMP,
			rampOut: region.rampOut ?? DEFAULT_ZOOM_RAMP,
		}));
		cursorMotionEasing = state.cursorMotionEasing ?? null;
	}

	return {
		// Getters (reactive reads)
		get videoPath() { return videoPath; },
		set videoPath(v: string) { videoPath = v; },

		get metadata() { return metadata; },
		set metadata(v: VideoMetadata | null) { metadata = v; },

		get thumbnailStrip() { return thumbnailStrip; },
		set thumbnailStrip(v: string[]) { thumbnailStrip = v; },

		get currentTime() { return currentTime; },
		set currentTime(v: number) { currentTime = v; },

		get isPlaying() { return isPlaying; },
		set isPlaying(v: boolean) { isPlaying = v; },

		get trimStart() { return trimStart; },
		set trimStart(v: number) { pushUndoState(); trimStart = v; },

		get trimEnd() { return trimEnd; },
		set trimEnd(v: number) { pushUndoState(); trimEnd = v; },

		get backgroundType() { return backgroundType; },
		set backgroundType(v: BackgroundType) { pushUndoState(); backgroundType = v; },

		get backgroundValue() { return backgroundValue; },
		set backgroundValue(v: string) { pushUndoState(); backgroundValue = v; },

		get backgroundBlur() { return backgroundBlur; },
		set backgroundBlur(v: number) { backgroundBlur = v; },

		get padding() { return padding; },
		set padding(v: number) { padding = v; },

		get borderRadius() { return borderRadius; },
		set borderRadius(v: number) { borderRadius = v; },

		get layoutMode() { return layoutMode; },
		set layoutMode(v: LayoutMode) { pushUndoState(); layoutMode = v; },

		get zoomRegions() { return zoomRegions; },

		get cursorSamplesRaw() { return cursorSamplesRaw; },
		set cursorSamplesRaw(v: CursorSampleLike[]) { cursorSamplesRaw = v; },

		get selectedZoomRegionId() { return selectedZoomRegionId; },
		set selectedZoomRegionId(v: string | null) { selectedZoomRegionId = v; },

		get cursorMotionEasing() { return cursorMotionEasing; },
		set cursorMotionEasing(v: Easing | null) { pushUndoState(); cursorMotionEasing = v; },

		get cursorSettings() { return cursorSettings; },
		set cursorSettings(v: CursorSettings) { cursorSettings = v; },

		get audioSettings() { return audioSettings; },
		set audioSettings(v: AudioSettings) { audioSettings = v; },

		get watermarkSettings() { return watermarkSettings; },
		set watermarkSettings(v: WatermarkSettings) { watermarkSettings = v; },

		get exportFormat() { return exportFormat; },
		set exportFormat(v: ExportFormat) { exportFormat = v; },

		get exportQuality() { return exportQuality; },
		set exportQuality(v: ExportQuality) { exportQuality = v; },

		get exportProgress() { return exportProgress; },
		set exportProgress(v: number | null) { exportProgress = v; },

		get isExporting() { return isExporting; },
		set isExporting(v: boolean) { isExporting = v; },

		get timelineZoom() { return timelineZoom; },
		set timelineZoom(v: number) { timelineZoom = v; },

		get canUndo() { return undoStack.length > 0; },
		get canRedo() { return redoStack.length > 0; },

		// Methods
		undo,
		redo,
		pushUndoState,
		setBackground,
		updateCursorSettings,
		updateAudioSettings,
		updateWatermarkSettings,
		addZoomRegion,
		removeZoomRegion,
		updateZoomRegion,
		selectZoomRegion,
		reset,
		toRenderState,
		loadRenderState,
	};
}

export type EditorStore = ReturnType<typeof createEditorStore>;
